services:

 db:
  image: postgres:15
  environment:
    POSTGRES_USER: postgres
    POSTGRES_PASSWORD: postgres
    POSTGRES_DB: gateway
  ports:
    - 5432:5432
  volumes:
    - postgres_data:/var/lib/postgresql/data
  healthcheck:
    test: ["CMD", "pg_isready", "-U", "postgres", "-d", "gateway"]
    interval: 10s
    timeout: 5s
    retries: 5
  restart: always
  
volumes:
  postgres_data:
